#!/bin/bash
#
# "Daemon" scripts that generates a new index.html file
# which is our feed every 15 minutes
#
# twint has been explicitly installed to make thing convenient
#


# Use a python tool twint to fetch all the tweets in the covid_19_bh20
# biohackathon
store_tweets () {
    FILE=tweets.txt
g    twint -s "#covid_19_bh20" --limit 10 > $FILE
    while read -r line; do
        redis-cli rpush BioHackathonTweets "$line";
    done < $FILE
}

while true; do
    redis-cli del BioHackathonTweets
    store_tweets
    racket feed.rkt
    sleep 60
done
